[package]
name = "chat_server_encrypt"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4.6"
num-traits = "0.2.19"
rand = "0.8.5"
block-modes = "0.8"
aes = "0.8"
tokio = { version = "1.40.0", features = ["full"] }

